### ISSUE TITLE
Other version of typst-preview binary

### ISSUE THREAD

**Issue by Isrothy** [chomosuke/typst-preview.nvim#15]
First of all, thank you for your execellent plugin.

I recently find this plugin dosen't work with my typst file. But the vscode plugin works fine.

Then I came up with a hack, which is replacing the one in `vim.fn.stdpath 'data' .. '/typst-preview/` by the vscode one. And it works.

I wounder if it can be possible to add a configuration option in `setup()` to set the path of `typst-preview` cli program?

**Comment by chomosuke** [comment]
Yes, I agree it would be nice. I don't have any time to work on this anytime soon but I would be happy to review a PR if you'd like to create one.

You might find #11 a good example of adding a option to `setup()`.

**Comment by goombaActivist** [comment]
What worked for me was noticing that the autoCmds are only created if typst-preview.nvim recognizes the file as .typ in the cwd.

So I downloaded the ftdetect file from this URL *https://github.com/kaarmu/typst.vim/tree/main/ftdetect* and placed in 
.config/nvim/ftdetect and it worked.
