### ISSUE TITLE
Bug(?): Scroll doesn't always follow cursor

### ISSUE THREAD

**Issue by mizlan** [chomosuke/typst-preview.nvim#16]
Havent sufficiently debugged this just yet, but wondering if it is normal for, e.g., the preview page not to scroll when I type `gg` to go to the top of the buffer. Sometimes I have to type something to get it to scroll, and sometimes even that doesn't work—I might have to go back into normal mode and type something again for it to finally scroll. Is this a known issue?

**Comment by chomosuke** [comment]
I think, maybe you have a bunch of functions defined at the top or maybe some `#set`. You have to move your cursor on top of content for it to follow. I'd imagine this issue exist in VSCode too and it's hard to think of a correct behavior for all cases.
