### ISSUE TITLE
Instalation on Windows doesn't work

### ISSUE THREAD

**Issue by paugarcia32** [chomosuke/typst-preview.nvim#2]
Hi, I am trying to install the plugin on windows, but it is failing all the time.

I've noticed that it is installing the plugin on the wrong directory

On this image, the directory on is suposed to be installed doesn't exists:

![imagen](https://github.com/chomosuke/typst-preview.nvim/assets/37461446/6895a8fc-2b7b-4963-8637-b5b6c8d3587d)

The reso of pluggins are installed on this directory:

![imagen](https://github.com/chomosuke/typst-preview.nvim/assets/37461446/a83a5892-6611-402e-8557-26b258203e42)

I hope you can solve this problem, I would love to try this plugin!

**Comment by chomosuke** [comment]
Hi there,

I am so far unable to reproduce your problem. It seems to be installing in the right directory for me 
![image](https://github.com/chomosuke/typst-preview.nvim/assets/38484873/a7d05416-faff-4971-96ab-7118bc7228e2)

Before I ask you for more details though, would you please try again with the latest release? I've just fixed another issue on #3 and this could be related to that.

Thanks!
