### ISSUE TITLE
Stuck on an old Typst-version

### ISSUE THREAD

**Issue by asmund20** [chomosuke/typst-preview.nvim#30]
The newest features of Typst, such as table.cell breaks my preview. As far as I can tell from reading the merged PRs, typst 0.11.0 should work, which is where this element was added. Both my Mason and Packer are up to date (called PackerSync and updated in Mason).
My nvim config is here: [nvim-config](https://github.com/asmund20/nvim-config)
Any help or clarifications would be much appreciated!

**Comment by chomosuke** [comment]
I can see in your config, you're specifying version `0.1.*`. You would need to change that to `0.2.*`. I noticed how I never updated that in README so I'll be doing that soon. Thanks for pointing this out.
