### ISSUE TITLE
Feature Request: Add command to toggle "invert_colors"

### ISSUE THREAD

**Issue by wnhrt** [chomosuke/typst-preview.nvim#36]
Normally I want to use the 'auto' mode to invert colors. On some occasions I would like to toggle the active state (inverted/not inverted) manually.
Currently I only see the option to edit the configuration or switch the dark mode of the browser and restart nvim/the preview.

A command or similar solution to dynamically switch the inversion state at runtime would be helpful.

**Comment by chomosuke** [comment]
Sorry I can not implement that. You would have to request the feature on [tinymist](https://github.com/Myriad-Dreamin/tinymist). Please reopen this issue when this becomes an available feature on tinymist.

**Comment by AdityaB4** [comment]
I wanted something similar to @wnhrt but I almost always control dark mode manually. Came up with this binding as a hack since tinymist does not support changing theme at runtime yet.

```lua
    vim.keymap.set("n", "<leader>td", function()
      local typst_preview = require("typst-preview")
      local config = require("typst-preview.config")
      
      local dark_mode = config.invert_colors == "always"
      
      local new_invert_setting = dark_mode and "never" or "always"
      
      vim.cmd("TypstPreviewStop")
      
      -- Get existing config and override just the invert_colors setting
      local new_config = vim.tbl_deep_extend("force", config, {
        invert_colors = new_invert_setting
      })
      
      typst_preview.setup(new_config)
      
      vim.defer_fn(function()
        vim.cmd("TypstPreviewToggle")
      end, 200)
      
      local mode_text = (not dark_mode) and "enabled" or "disabled"
      vim.notify("Typst preview: Dark mode " .. mode_text, vim.log.levels.INFO)
    end, { 
      buffer = true, 
      desc = "[T]ypst [D]ark mode toggle" 
    })

```

While this kills the old preview process, you'd still have to manually close the stale preview tab/window.

Hope this helps!
