### ISSUE TITLE
Vim Plug E121: Undefined variable: do

### ISSUE THREAD

**Issue by jjanella** [chomosuke/typst-preview.nvim#40]
Adding `Plug 'chomosuke/typst-preview.nvim', {'tag': 'v0.3.*', do: ':TypstPreviewUpdate'}` to my config causes:
```
E121: Undefined variable: do
E116: Invalid arguments for function plug#
```

My solution was to do `Plug 'chomosuke/typst-preview.nvim', {'tag': 'v0.3.*'}` instead and manually call `':TypstPreview`

**Comment by chomosuke** [comment]
Hi, I see. It's really difficult for me to test this as I don't use Vim Plug myself but I'll trust you on this one.

I've modify the installation instruction in README.md.
