### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by asmund20** [chomosuke/typst-preview.nvim#48]
Just setup my [config](https://github.com/asmund20/nvim) on a freshly installed Ubuntu 24.04 LTS. 

It does not download the typst preview binaries when I run :TypstPreviewUpdate. With debug on, nothing is shown when I run :mes. It does not appear to do anything. There is no folder in my .local/share/nvim for typst-preview. It works on my laptop. Please help!

When I run :TypstPreview, it obviously fails due to not finding the binary.

**Comment by justanotherscriptkiddienerd** [comment]
Honestly, the best solution probably is to reinstall. Also, preferably use a new image, your starting one may have been corrupted...
If you can't/don't want to, just google it. That's all I've got. 
Good luck!

**Comment by asmund20** [comment]
Think I found the issue, though I will not be able to test before tomorrow. 

Think the issue is that the binaries are downloaded using brew and that I have not installed that. (Binaries are downloaded in [fetch.lua, line 130](https://github.com/chomosuke/typst-preview.nvim/blob/master/lua/typst-preview/fetch.lua) using brew)

If that is indeed the problem, I will close this issue and make another one requesting a check for brew and an error message if brew is not found.

**Comment by asmund20** [comment]
Will likely make a PR implementing this error handling instead than an issue.

**Comment by justanotherscriptkiddienerd** [comment]
Good luck!

**Comment by asmund20** [comment]
Homebrew dependency was indeed the issue. Will look further into making either an issue or pr for printing an error message when running :TypstPreviewUpdate if homebrew is not installed on the system tomorrow.

**Comment by chomosuke** [comment]
Hey, sorry for the late reply, Does mac not have curl install by default? You should not need homebrew for this plugin, only curl

**Comment by asmund20** [comment]
You are right, of course. For some reason I thought that it was homebrew but it is using curl. I somehow read brew instead of curl in the code and installed curl to install homebrew, so tricked myself there. 

I am on Ubuntu, and did not have curl installed by default. So there should be an error message if curl is not installed. I can look into that.
