### ISSUE TITLE
Add support for PDF readers (Sioyek)

### ISSUE THREAD

**Issue by FahimAnayet** [chomosuke/typst-preview.nvim#50]
Some pdf readers supports forward and backward sync and also quite fast. So if possible please do add. Thanks. But, I love this plugin anyway.

**Comment by max397574** [comment]
that doesn't make much sense
because always compiling the document won't be as fast as this currently is

you could just use typst watch, an autocmd on BufWrite and open the pdf in a pdf viewer

**Comment by FahimAnayet** [comment]
Yeah make sense.  Anyway thank you for your reply 😃
