### ISSUE TITLE
Package vartable freeze

### ISSUE THREAD

**Issue by fabius32** [chomosuke/typst-preview.nvim#53]
Hi,
I have a problem with the package vartable.

When I write "#import "@preview/vartable:0.1.0": * " , it freeze the preview.

Tested with safari and Firefox on MacOs.

Thank you

**Comment by chomosuke** [comment]
hello, I can not reproduce this with the latest version. It's possible that recent changes has already fixed this issue. If not, can you install tinymist as an LSP and make sure there are no error in your typst file as the preview would freeze if there's an error in your typst file.

Feel free to reopen this issue if the error presist.
