### ISSUE TITLE
wrong cursor syncing on headings

### ISSUE THREAD

**Issue by max397574** [chomosuke/typst-preview.nvim#54]
I'm not 100% sure whether this is a bug or not but when you move the cursor onto a heading the preview moves up to the TOC

if this is intended behavior this should definitely be configurable because it causes a lot of confusing movement in the preview

**Comment by asmund20** [comment]
Pretty sure this is handled by the binary, which is from [enter-tainer/typst-preview](https://github.com/Enter-tainer/typst-preview) and is depracted. I recommend setting the typst-preview binary to tinymist for the updated version. This might be solved there. If not, I recommend making an issue in the tinymist repository.

**Comment by max397574** [comment]
👍
