### ISSUE TITLE
⬆️ Update Tinymist release

### ISSUE THREAD

**Issue by rwmpelstilzchen** [chomosuke/typst-preview.nvim#60]
Thanks for typst-preview.nvim! It’s brilliant! ^_^

[Version 0.12.0 of Tinymist](https://github.com/Myriad-Dreamin/tinymist/releases/tag/v0.12.0) has been recently released. I think this is the line to update here: https://github.com/chomosuke/typst-preview.nvim/blob/0f43ed7fa661617751bfd0ca2f01ee13eba6569e/lua/typst-preview/fetch.lua#L177

Will this make typst-preview.nvim compile with Typst 0.12?

**Comment by cskeeters** [comment]
Man, I'm chompin' at the bit to use the new version too.  As a work around, I used `dependencies_bin` as described in README.md

```
dependencies_bin = {
  ['tinymist'] = "/opt/homebrew/bin/tinymist"
},
```
