### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by THuouRY** [chomosuke/typst-preview.nvim#63]
I currently use your amazing plugin to write pretty much everything. I would really appreciate it if it could have a feature for dark mode preview. I tried playing with the HTML and CSS previewed on my browser without any result. This is really important to me since Neovim is in dark mode while the preview is a shining white, which causes pain to my eyes.

**I really appreciate your work!**

**Comment by asmund20** [comment]
Check the readme configuration. Setting invert colors to always will invert everything. You can also choose to not invert images or set it to auto.

**Comment by chomosuke** [comment]
Hi @THuouRY, Thank you for your kind words :>. 

As @asmund20 has said, you can set `invert_colors` to achieve the desired effect.
