### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dib-Roy** [chomosuke/typst-preview.nvim#64]
**Before you start**
- [x] You've headed over to
  [tinymist](https://github.com/Myriad-Dreamin/tinymist) and can confirm that
  the issue does not exist with the [VS Code plugin for
  tinymist](https://marketplace.visualstudio.com/items?itemName=myriad-dreamin.tinymist).

**Describe the bug**
I'm not sure if this is a bug with typst-preview specifically but I am trying to use [qutebrowser](https://www.qutebrowser.org/) to preview the file rather than firefox. Unfortunately copying the link only results in a grey window.

**To Reproduce**
1. Open a live preview
2. Paste the link into qutebrowser
3. Observe the grey screen

**Expected behavior**
See the preview as expected.

**Screenshots**
The same link is open in both browsers below.
![image](https://github.com/user-attachments/assets/f08bbded-bad9-4b94-86c5-25e6431ca2df)

**Desktop (please complete the following information):**
 - OS: Arch
 - Commit / Version: 1.1

**Comment by chomosuke** [comment]
Hi, the communication and rendering in the browser is completely handled by tinymist. As such, I will not be able to help with this issue. Please kindly head over to tinymist and raise the issue there.
Thank you.
