### ISSUE TITLE
[FEATURE] Respect `TYPST_ROOT` envar

### ISSUE THREAD

**Issue by meck** [chomosuke/typst-preview.nvim#65]
I had issues getting the previews working, discovered it was because the default `get_root` function dosen't respect the `TYPST_ROOT` envar. After settings it to:
```
    require('typst-preview').setup {
      get_root = function(path_of_main_file)
        local root = os.getenv("TYPST_ROOT")
        if root then 
          return root 
        end
        return vim.fn.fnamemodify(path_of_main_file, ':p:h')
      end,
    }
```

Everything seems to work, this might be a candidate for the default settings, or at least the docs?

**Comment by chomosuke** [comment]
Heyo and good morning,

Thanks for bringing this up. If you'd like to create an PR making this default and updating the doc (both `doc/typst-preview.nvim.txt` and `README.md`) I'll be more than happy to accept it.

**Comment by chomosuke** [comment]
completed in #71
