### ISSUE TITLE
[FEATURE] Download executables as needed, instead of during `build` step

### ISSUE THREAD

**Issue by stefanboca** [chomosuke/typst-preview.nvim#67]
When using `lazy.nvim`, if a user specifies, for instance
```lua
dependencies_bin = {
  tinymist = "tinymist",
},
```
in opts, and configures the build step as per the README, tinymist will get downloaded by the build step when the plugin is first installed - **even though** the user has specified not to download by setting `dependencies_bin`. This is because during install, the plugin is not setup during build - see https://github.com/folke/lazy.nvim/issues/1806.

Instead of having a build step, it would be preferable for binaries to be downloaded lazily when `:TypstPreview` is run for the first time.

**Comment by 2giosangmitom** [comment]
I have an idea to set the `dependencies_bin` before the plugin setup. Specifically, I propose moving `dependencies_bin` to `vim.g`.

I modified config.lua for testing as follows:

```lua
local M = {
  opts = {
    debug = false,
    open_cmd = nil,
    invert_colors = 'never',
    follow_cursor = true,
    dependencies_bin = vim.g.typst_preview_dependencies_bin or {
      ['tinymist'] = nil,
      ['websocat'] = nil,
    },
    extra_args = nil,
    get_root = function(path)
      return vim.fn.fnamemodify(path, ':p:h')
    end,
    get_main_file = function(path)
      return path
    end,
  },
}
-- rest of the original code
```

This is how I setup the plugin with lazy
```lua
{
  "chomosuke/typst-preview.nvim",
  init = function()
    vim.g.typst_preview_dependencies_bin = {
      tinymist = "tinymist",
    }
  end,
  opts = {},
}
```

From my testing, this successfully skipped the download for `tinymist`.

**Comment by stefanboca** [comment]
Alternatively, the binaries could be downloaded during `setup`, removing the need for a build step.

**Comment by chomosuke** [comment]
Hi, sorry for the late reply.

In my opinion I do see a lot of difference between getting told to run an extra command when `:TypstPreview` is ran for the first time and having it automatically be downloaded when `:TypstPreview` is ran. It is just the difference between one command.

I'll add an option to `update()` to ignore certain binary though.

**Comment by 2giosangmitom** [comment]
Thank you! I’m looking forward to seeing your implementation.

**Comment by p-98** [comment]
Nice to see this merged!
@chomosuke Unfortunately, currently the readme is inconsistent (I think). It states the update is automatically called on setup, but installing via the snippet, specifically using`version = '1.*'`, installs `1.1.0`, wich does not contain the change.
So probably a new version tag `1.2.0` would fix this problem.
