### ISSUE TITLE
Add option to overwrite open link shell command

### ISSUE THREAD

**Issue by geeker-one** [chomosuke/typst-preview.nvim#7]
If it can be configured, I would be very grateful.

**Comment by chomosuke** [comment]
It is not yet implemented yet, I will implement it sometimes next month.

**Comment by jskherman** [comment]
+1, it would be nice to pass a different `open_cmd` (e.g. to use a less bloated browser) to the [logic here](https://github.com/chomosuke/typst-preview.nvim/blob/eca78fffe12c350e0147de228e570efd2851d024/lua/typst-preview/utils.lua#L42C1-L51C4) from the plugin setup.

Sorry for the noob question (I'm new to vim/nvim) but would getting the custom `open_cmd` parameter from the `require'typst-preview'.setup{}` via the local `config` variable (`config.opts.open_cmd` like `config.opts.debug`?) in the `utils.lua` file be the way to go?

**Comment by chomosuke** [comment]
Good morning,

I have gotten a little bit more busy recently and probably won't be able to implement this util February. However, I would be grateful if one of you @jskherman @geeker-one would make a pull request implementing and documenting this feature. I am thinking of an option that if not `nil`  would overwrite `cmd` on `utils.lua` line 56.
