### ISSUE TITLE
Live preview isn't working

### ISSUE THREAD

**Issue by stevenxxiu** [chomosuke/typst-preview.nvim#8]
The first render works, however:

- I can't get live preview to work.
- Scrolling in the browser does nothing in the editor.

To test:

- I create a file with `1` in it.
- Run `:TypstPreview`. This opens up a browser tab.
- Change the `1` to `2` and save.
- The live preview doesn't change.

I also tried to have this plugin as my only *Lazy* plugin, but the same thing occurs.

My config:

```lua
return {
  'chomosuke/typst-preview.nvim',
  lazy = false,
  version = '0.1.*',
  opts = {
    debug = true,
  },
  build = function() require 'typst-preview'.update() end,
}
```

My [messages](https://github.com/chomosuke/typst-preview.nvim/files/13692375/messages.txt).

**Comment by VoxelMC** [comment]
I am also experiencing this.

**Comment by wisp3rwind** [comment]
Same here.

This sounds a bit like https://github.com/Enter-tainer/typst-preview/issues/81, but that should be fixed.

**Comment by chomosuke** [comment]
Hi,

Sorry for the late response.

I followed your steps and am unable to reproduce your issue. The preview on my machine updated as soon as I replaced `1` with`2`.

Here are my messages, I can not spot any differences except that I have 4 `TypstActor` log and you only have 2.
[message.txt](https://github.com/chomosuke/typst-preview.nvim/files/13848202/message.txt)

This looks like an upstream issue, if you can reproduce the same problem with the VSCode plugin (using the same browser) then please do open an issue in https://github.com/Enter-tainer/typst-preview.

This can also be an browser or OS specific issue. Fyi I uses chrome on Arch.

**Comment by stevenxxiu** [comment]
Hi interesting, it seems to work now. I'm not really sure what I didn't do right before. Here's my config now:

```lua
return {
  'chomosuke/typst-preview.nvim',
  lazy = true,
  ft = 'typst',
  opts = {
    get_root = function(bufnr)
      return vim.api.nvim_buf_get_name(bufnr):match('(.*/)')
    end,
  },
  build = function()
    require('typst-preview').update()
  end,
}
```

I'm also on *Arch Linux*, with *Vivaldi* 6.5.3206.50-1.

Thanks for the plugin!

**Comment by VoxelMC** [comment]
> Hi interesting, it seems to work now. I'm not really sure what I didn't do right before. Here's my config now:
> 
> ```lua
> return {
>   'chomosuke/typst-preview.nvim',
>   lazy = true,
>   ft = 'typst',
>   opts = {
>     get_root = function(bufnr)
>       return vim.api.nvim_buf_get_name(bufnr):match('(.*/)')
>     end,
>   },
>   build = function()
>     require('typst-preview').update()
>   end,
> }
> ```
> 
> I'm also on _Arch Linux_, with _Vivaldi_ 6.5.3206.50-1.
> 
> Thanks for the plugin!

This also fixed it for me - life saver! Have a great day :)

**Comment by wisp3rwind** [comment]
Also working for me now — maybe it's https://github.com/Enter-tainer/typst-preview/pull/212, which fixes https://github.com/Enter-tainer/typst-preview/issues/211?

**Comment by SuperCowProducts** [comment]
Hi @stevenxxiu, I was getting an error with your script (clearly the updates after all these years have invalidated it), so I fed it into [Ecosia AI Chat](https://www.ecosia.org/ai-chat) to get this, which worked for me (Firefox only for me, Chromium just always displays a blank page for me):
```lua
return {
  "chomosuke/typst-preview.nvim",
  lazy = true,
  ft = "typst",
  opts = {
    get_root = function(bufnr)
      -- Ensure bufnr is a number
      bufnr = tonumber(bufnr) or vim.api.nvim_get_current_buf()
      return vim.api.nvim_buf_get_name(bufnr):match("(.*/)")
    end,
  },
  build = function()
    require("typst-preview").update()
  end,
}
```
