### ISSUE TITLE
Browser only produces a grey screen when running `TypstPreview`

### ISSUE THREAD

**Issue by HiramTheHero** [chomosuke/typst-preview.nvim#9]
Everything seems to be installed correctly:

<img width="826" alt="Screenshot 2023-12-28 at 10 07 44 PM" src="https://github.com/chomosuke/typst-preview.nvim/assets/22198719/9ae08d62-6b27-4f32-9a44-08629cf67351">

When I run `TypstPreview` I get the following in my browser (Thorium & Firefox):

<img width="952" alt="Screenshot 2023-12-28 at 10 05 15 PM" src="https://github.com/chomosuke/typst-preview.nvim/assets/22198719/3acc9243-ea97-44f5-958a-8b2f5ae511a7">

Any thoughts on what is going wrong? I'm on an M1 Mac. If there's more helpful info I can get for you all, please let me know how. I'm happy to do so.

Thank you for your work on this project!

**Comment by HiramTheHero** [comment]
The plugin is working now. Not sure why it was having issues.

**Comment by cskeeters** [comment]
For anyone else having this issue:
1) Remove or update `version = '0.1.*',` in Lazy.nvim configuration.
2) Restart neovim
3) Run TypstPreviewUpdate to download new binaries into `.local/share/...`

**Comment by schl3sch** [comment]
I also got the same problem. On my linux laptop everything works fine, but when I run it in the wsl with the same config, the preview in the browser shows always a grey screen. Removing the version does not fix the issue.
